- name: Testing
  hosts: localhost
  gather_facts: false
  vars:
    amz_grafana_packages: "{{ amz_grafana_url }}{{ amz_version }}{{ amz_grafana_arch }}"
    amz_grafana_url: "https://dl.grafana.com/oss/release/grafana-"
    amz_grafana_arch: ".x86_64.rpm "
    amz_version: "9.5.1-1"
  tasks:
    - name: Testing
      debug:
        var: amz_grafana_packages
        
      